### ISSUE TITLE
quasar dev returns errors

### ISSUE THREAD

**Issue by ghost** [eosdac/eosdac-factory#1]
Hi,
I followed the steps in the video and at the last step when I have to run `quasar dev` , I get the following error:
 app:paths ⚠️  Error. This command must be executed inside a Quasar v0.15+ project folder. +0ms
 app:paths For Quasar pre v0.15 projects, npm uninstall -g quasar-cli; npm i -g quasar-cli@0.6.5 +3ms

I did run those npm commands they suggested but I still get the same error. Any ideas?

**Comment by criadoperez** [comment]
Make sure you install quasar with the "-g" command, so it's global.
Also, I don't know if this can help, but I also encountered several problems when I was using:

- Quasar CLI v.0.17.24
- Quasar Framework v.0.17.20

 I switched to:

- Quasar CLI v.0.17.23
- Quasar Framework v.0.17.19

And it worked!

**Comment by ghost** [comment]
Thanks, I see I have the following versions:
`~/dac-factory# quasar --version
0.17.24`

I can't seem to be able to remove despite `npm uninstall -g quasar-cli@0.17.24`. Any tips?

**Comment by lukestokes** [comment]
You'll need to be in the memberclient folder. You can also just run npm start: https://github.com/eosdac/memberclient
