### ISSUE TITLE
Verify amount of ram needed for each account.

### ISSUE THREAD

**Issue by ajose01** [eosdac/eosdac-factory#9]
It seems the amount of ram being bought requires a large amount of EOS in order to test out. From `functions.sh`
```
 eval "cleos --wallet-url $WALLET_URL -u $API_URL system newaccount --stake-cpu \"5.0000 EOS\" --stake-net \"1.0000 EOS\" --transfer --buy-ram-kbytes 2048 $creator $act $key"
```

Should that be `--buy-ram-bytes 2048` ?

**Comment by str** [comment]
@ajose01 This is not an DAC related question, nor is this an EOS forum.

You can see a related question answered here: 

https://eosio.stackexchange.com/questions/765/what-is-the-minimum-bytes-required-for-a-new-account

**Comment by ajose01** [comment]
@str Thanks. Although the question is specific to the `./eosfactory.sh` script from eosdac-factory, which uses `./functions.sh`, hence the question here.

I can modify the script, but I am not sure if there's a reason why eosdac configured it with such high ram.

**Comment by str** [comment]
I'm going to close this issue as the creation of the accounts is done by the factory
